		<!--Codi per a la politica de Cookies -->	 
		<div class="cookiesms" id="cookie1">
		Esta web utiliza cookies, puedes ver nuestra  <a href="#">la pol&iacute;tica de cookies, aqu&iacute;</a> 
		Si continuas navegando est&aacute;s acept&aacute;ndola
		<button onclick="controlcookies()">Aceptar</button>
		<div  class="cookies2" onmouseover="document.getElementById('cookie1').style.bottom = '0px';">Pol&iacute;tica de cookies + </div>
		</div>
		<script type="text/javascript">
		if (localStorage.controlcookie>0){ 
		document.getElementById('cookie1').style.bottom = '-50px';
		}
		</script>
		<!-- Fin del código de cookies --->